import fs from 'node:fs';
import path from 'node:path';
import {randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {json,parse,now,fail,text} from './lib.mjs';
const digest=v=>createHash('sha256').update(v).digest('hex');
function encodePassword(password){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex')}
function checkPassword(password,encoded){if(typeof password!=='string'||password.length>512||!encoded)return false;const[salt,value]=encoded.split(':');if(!salt||!value)return false;const a=scryptSync(password,salt,64),b=Buffer.from(value,'hex');return a.length===b.length&&timingSafeEqual(a,b)}
export function createSecrets(dir){
 const secretDir=process.env.FINOPS_SECRETS_DIR||dir;fs.mkdirSync(secretDir,{recursive:true,mode:0o700});const file=path.join(secretDir,'secrets.json');let data=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{};
 function save(){const temp=file+'.tmp';fs.writeFileSync(temp,json(data),{mode:0o600});fs.renameSync(temp,file);}
 if(!data.password){const password=process.env.FINOPS_INITIAL_PASSWORD||randomBytes(15).toString('base64url');data.password=encodePassword(password);fs.writeFileSync(path.join(dir,'initial-login.txt'),`LLMFinOps\n用户名: admin\n初始密码: ${password}\n首次登录后可在设置中修改。\n`,{mode:0o600});}
 if(!data.ingestToken)data.ingestToken=randomBytes(32).toString('base64url');data.accounts||={};save();
 return{checkPassword:p=>checkPassword(p,data.password),setPassword:(old,value)=>{if(!checkPassword(old,data.password))fail('当前密码不正确',403);if(typeof value!=='string'||value.length<12||value.length>200)fail('新密码至少 12 位，最多 200 位');data.password=encodePassword(value);save();try{fs.unlinkSync(path.join(dir,'initial-login.txt'))}catch{}},token:()=>data.ingestToken,rotateToken:()=>{data.ingestToken=randomBytes(32).toString('base64url');save();return data.ingestToken},account:id=>data.accounts[id]||{},setAccount:(id,v)=>{data.accounts[id]={...data.accounts[id],...v};save()},resolve:(id,kind='key')=>{const a=data.accounts[id]||{};if(a[kind])return a[kind];if(a[kind+'File']){try{return fs.readFileSync(a[kind+'File'],'utf8').trim()}catch{return''}}return''},notification:()=>data.notification||{},setNotification:v=>{data.notification=v;save()}};
}
export function authMiddleware(store,secrets){
 const attempts=new Map();const sweep=setInterval(()=>{const t=Date.now();for(const[k,v]of attempts)if(t-v.at>900000)attempts.delete(k);store.run('DELETE FROM sessions WHERE expires_at<?',now())},300000);sweep.unref();
 const cookie=req=>String(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('finops_session='))?.slice(15)||'';
 const authenticated=req=>{let token=cookie(req);return token&&store.one('SELECT id FROM sessions WHERE id=? AND expires_at>?',digest(token),now())};
 const secure=req=>req.secure||String(req.headers['x-forwarded-proto']||'').split(',')[0]==='https';
 const setCookie=(req,res,value,maxAge)=>res.setHeader('Set-Cookie',`finops_session=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${secure(req)?'; Secure':''}`);
 return{authenticated,checkOrigin:(req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const origin=req.headers.origin;if(origin){let host;try{host=new URL(origin).host}catch{return res.status(403).json({error:'来源无效'})}if(host!==req.headers.host)return res.status(403).json({error:'仅允许同源请求'})}next()},require:(req,res,next)=>{if(!authenticated(req))return res.status(401).json({error:'请先登录'});next()},ingest:(req,res,next)=>{let token=String(req.headers.authorization||'').replace(/^Bearer /,'');const a=Buffer.from(token),b=Buffer.from(secrets.token());if(!token||a.length!==b.length||!timingSafeEqual(a,b))return res.status(401).json({error:'采集凭据无效'});next()},login:(req,res)=>{const key=req.ip||'local',entry=attempts.get(key)||{count:0,at:Date.now()};if(entry.count>=15&&Date.now()-entry.at<900000)return res.status(429).json({error:'登录尝试过多，请 15 分钟后再试'});if(req.body.username!=='admin'||!secrets.checkPassword(req.body.password)){attempts.set(key,{count:entry.count+1,at:entry.at});return res.status(401).json({error:'用户名或密码不正确'})}attempts.delete(key);const token=randomBytes(32).toString('base64url');store.run('INSERT INTO sessions VALUES (?,?)',digest(token),new Date(Date.now()+30*86400000).toISOString());setCookie(req,res,token,30*86400);res.json({ok:true,user:{name:'Jingxuan',username:'admin'}})},logout:(req,res)=>{store.run('DELETE FROM sessions WHERE id=?',digest(cookie(req)));setCookie(req,res,'',0);res.json({ok:true})},close:()=>clearInterval(sweep)};
}
