import fs from 'node:fs';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {now,uid,json,parse,normalizeCall,priceCall,range,stats,groupStats,localDay,addDay,fail,num,text,required,date as validDate} from './lib.mjs';
export function createStore(dir){
 fs.mkdirSync(dir,{recursive:true,mode:0o700});
 const db=new DatabaseSync(path.join(dir,'finops.sqlite'));db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,name TEXT NOT NULL,provider TEXT NOT NULL,billing_mode TEXT NOT NULL DEFAULT 'api',currency TEXT NOT NULL DEFAULT 'USD',billing_group TEXT,notes TEXT DEFAULT '',low_balance REAL,runway_days REAL DEFAULT 3,enabled INTEGER NOT NULL DEFAULT 1,sync_status TEXT DEFAULT 'not_configured',last_sync TEXT,last_error TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS calls(id TEXT PRIMARY KEY,trace_id TEXT NOT NULL,project TEXT NOT NULL,environment TEXT NOT NULL,provider TEXT NOT NULL,account_id TEXT NOT NULL,feature TEXT NOT NULL,model TEXT NOT NULL,requested_model TEXT,started_at TEXT NOT NULL,ended_at TEXT,local_day TEXT NOT NULL,status TEXT NOT NULL,duration_ms REAL,ttft_ms REAL,input_tokens INTEGER,output_tokens INTEGER,cached_tokens INTEGER,reasoning_tokens INTEGER,total_tokens INTEGER,cost_low REAL,cost_high REAL,actual_cost REAL,currency TEXT,cost_source TEXT,pricing_id TEXT,attempt INTEGER,retry_of TEXT,fallback_from TEXT,error_code TEXT,request_id TEXT,source TEXT,scope TEXT,billing_mode TEXT,ingested_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS idx_calls_date ON calls(local_day,project,provider); CREATE INDEX IF NOT EXISTS idx_calls_trace ON calls(trace_id); CREATE INDEX IF NOT EXISTS idx_calls_account ON calls(account_id,local_day);
 CREATE TABLE IF NOT EXISTS traces(id TEXT PRIMARY KEY,label TEXT,project TEXT,started_at TEXT,duration_ms REAL,status TEXT,source TEXT);
 CREATE TABLE IF NOT EXISTS snapshots(id TEXT PRIMARY KEY,account_id TEXT NOT NULL,currency TEXT NOT NULL,balance REAL NOT NULL,granted REAL,topped_up REAL,source TEXT NOT NULL,observed_at TEXT NOT NULL,note TEXT DEFAULT '');
 CREATE INDEX IF NOT EXISTS idx_snapshots_account ON snapshots(account_id,observed_at);
 CREATE TABLE IF NOT EXISTS billing_daily(id TEXT PRIMARY KEY,account_id TEXT NOT NULL,day TEXT NOT NULL,provider_project TEXT NOT NULL DEFAULT '',line_item TEXT NOT NULL DEFAULT '',currency TEXT NOT NULL,amount REAL NOT NULL,source TEXT NOT NULL,observed_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS provider_usage(id TEXT PRIMARY KEY,account_id TEXT NOT NULL,day TEXT NOT NULL,model TEXT,api_key_id TEXT,provider_project TEXT,data TEXT NOT NULL,observed_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS pricing(id TEXT PRIMARY KEY,provider TEXT NOT NULL,model TEXT NOT NULL,input_rate REAL NOT NULL,cached_rate REAL NOT NULL,output_rate REAL NOT NULL,effective_from TEXT NOT NULL,source_url TEXT NOT NULL,note TEXT DEFAULT '',created_at TEXT NOT NULL,UNIQUE(provider,model,effective_from));
 CREATE TABLE IF NOT EXISTS budgets(id TEXT PRIMARY KEY,name TEXT NOT NULL,scope TEXT NOT NULL,scope_id TEXT NOT NULL DEFAULT '',period TEXT NOT NULL,amount REAL NOT NULL,threshold REAL NOT NULL DEFAULT .8,enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS alerts(id TEXT PRIMARY KEY,type TEXT NOT NULL,title TEXT NOT NULL,detail TEXT NOT NULL,severity TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',first_seen TEXT NOT NULL,last_seen TEXT NOT NULL,ack_at TEXT);
 CREATE TABLE IF NOT EXISTS connectors(id TEXT PRIMARY KEY,name TEXT NOT NULL,kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'waiting',last_seen TEXT,last_error TEXT,records INTEGER NOT NULL DEFAULT 0,config TEXT NOT NULL DEFAULT '{}');
 CREATE TABLE IF NOT EXISTS sync_runs(id TEXT PRIMARY KEY,account_id TEXT,kind TEXT,status TEXT,detail TEXT,started_at TEXT,ended_at TEXT);
 CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,expires_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 `);
 const all=(sql,...args)=>db.prepare(sql).all(...args),one=(sql,...args)=>db.prepare(sql).get(...args),run=(sql,...args)=>db.prepare(sql).run(...args);
 function setting(key,fallback){const r=one('SELECT value FROM settings WHERE key=?',key);return r?parse(r.value,fallback):fallback}
 function setSetting(key,v){run('INSERT OR REPLACE INTO settings VALUES (?,?)',key,json(v))}
 function ingest(values){
  if(!Array.isArray(values)||values.length>1000)fail('每批最多 1000 条调用');
  const normalized=values.map(v=>{let c=normalizeCall(v);const a=one('SELECT billing_mode FROM accounts WHERE id=?',c.account_id);if(a?.billing_mode==='subscription')c.billing_mode='subscription';const p=one('SELECT * FROM pricing WHERE provider=? AND model=? AND effective_from<=? ORDER BY effective_from DESC LIMIT 1',c.provider,c.model,c.started_at);return priceCall(c,p)});
  let inserted=0;db.exec('BEGIN');try{for(const c of normalized){const keys=Object.keys(c);inserted+=Number(run(`INSERT OR IGNORE INTO calls (${keys.join(',')}) VALUES (${keys.map(()=>'?').join(',')})`,...Object.values(c)).changes)}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}
  return{received:values.length,inserted,duplicates:values.length-inserted};
 }
 function where(q={}){const{start,end}=range(q);let w='local_day>=? AND local_day<=?',args=[start,end];for(const key of ['project','provider','environment','account_id','model','feature','status'])if(q[key]&&q[key]!=='all'){w+=` AND ${key}=?`;args.push(String(q[key]))}if(q.q){w+=' AND (model LIKE ? OR feature LIKE ? OR trace_id LIKE ? OR project LIKE ? OR error_code LIKE ?)';args.push(...Array(5).fill('%'+String(q.q).slice(0,100)+'%'))}if(q.fallback==='1')w+=' AND fallback_from IS NOT NULL';return{w,args,start,end}}
 function filtered(q={}){const{w,args}=where(q);return all(`SELECT * FROM calls WHERE ${w} ORDER BY started_at DESC`,...args)}
 function dashboard(q={}){const rows=filtered(q),{start,end}=range(q),days=Math.round((Date.parse(end)-Date.parse(start))/86400000)+1;const previous=filtered({...q,from:addDay(start,-days),to:addDay(start,-1)});const byDay=new Map(groupStats(rows,'local_day').map(r=>[r.name,r]));const timeline=[];for(let d=start;d<=end&&timeline.length<367;d=addDay(d,1))timeline.push(byDay.get(d)||{name:d,...stats([])});
  return{range:{start,end,timezone:'Europe/Paris'},summary:stats(rows),previous:stats(previous),timeline,providers:groupStats(rows,'provider'),projects:groupStats(rows,'project'),models:groupStats(rows,r=>r.provider+' / '+r.model),features:groupStats(rows,r=>r.project+' / '+r.feature),recent:rows.slice(0,8),filter_options:{projects:all('SELECT DISTINCT project name FROM calls ORDER BY name').map(x=>x.name),models:all('SELECT DISTINCT model name FROM calls ORDER BY name').map(x=>x.name),environments:all('SELECT DISTINCT environment name FROM calls ORDER BY name').map(x=>x.name)},alerts:all("SELECT * FROM alerts WHERE status='open' ORDER BY last_seen DESC LIMIT 6"),last_ingest:one('SELECT MAX(ingested_at) at FROM calls')?.at||null,total_records:one('SELECT COUNT(*) n FROM calls').n};
 }
 function listCalls(q={}){const{w,args}=where(q),page=Math.max(1,parseInt(q.page)||1),limit=Math.min(100,Math.max(1,parseInt(q.limit)||25));return{items:all(`SELECT * FROM calls WHERE ${w} ORDER BY started_at DESC LIMIT ? OFFSET ?`,...args,limit,(page-1)*limit),total:one(`SELECT COUNT(*) n FROM calls WHERE ${w}`,...args).n,page,limit}}
 function trace(id){const calls=all('SELECT * FROM calls WHERE trace_id=? ORDER BY started_at,attempt',id);if(!calls.length)fail('Trace 不存在',404);return{trace:one('SELECT * FROM traces WHERE id=?',id)||{id,project:calls[0].project,label:calls[0].feature},calls,summary:stats(calls)}}
 function accountView(a){const snaps=all('SELECT * FROM snapshots WHERE account_id=? ORDER BY observed_at DESC LIMIT 120',a.id);const seen=new Set(),latest=snaps.filter(s=>{if(seen.has(s.currency))return false;seen.add(s.currency);return true});const start=addDay(localDay(),-6),recent=all('SELECT * FROM calls WHERE account_id=? AND local_day>=?',a.id,start);const s=stats(recent),daily=(s.cost_high||0)/7;const usd=latest.find(x=>x.currency==='USD'),foreignFunds=latest.some(x=>x.currency!=='USD'&&x.balance>0);const runway=usd&&daily>0&&!foreignFunds?usd.balance/daily:null;
  return{...a,balances:latest,history:snaps.reverse(),usage7d:s,runway_days_estimate:runway,runway_unavailable_reason:foreignFunds?'currency-mismatch':!usd?'no-usd-balance':daily<=0?'no-observed-spend':null,bills:all('SELECT currency,SUM(amount) amount FROM billing_daily WHERE account_id=? AND day>=? GROUP BY currency',a.id,localDay().slice(0,7)+'-01')};
 }
 function accounts(){return all('SELECT * FROM accounts ORDER BY provider,name').map(accountView)}
 function saveAccount(v){const provider=required(v.provider,'provider');if(!['openai','deepseek','gemini','mimo','jev','codex','other'].includes(provider))fail('Provider 无效');const id=text(v.id)||uid('acct-'),existing=one('SELECT * FROM accounts WHERE id=?',id);const a={...existing,...v};const mode=['api','prepaid','postpaid','subscription','manual'].includes(a.billing_mode)?a.billing_mode:'api';const currency=['USD','EUR','CNY'].includes(a.currency)?a.currency:'USD';run(`INSERT INTO accounts(id,name,provider,billing_mode,currency,billing_group,notes,low_balance,runway_days,enabled,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,provider=excluded.provider,billing_mode=excluded.billing_mode,currency=excluded.currency,billing_group=excluded.billing_group,notes=excluded.notes,low_balance=excluded.low_balance,runway_days=excluded.runway_days,enabled=excluded.enabled`,id,required(a.name,'名称'),provider,mode,currency,text(a.billing_group)||null,text(a.notes,1000),num(a.low_balance),num(a.runway_days)??3,a.enabled===false||a.enabled===0?0:1,existing?.created_at||now());return one('SELECT * FROM accounts WHERE id=?',id)}
 function snapshot(v){if(!one('SELECT id FROM accounts WHERE id=?',v.account_id))fail('账户不存在');const balance=num(v.balance);if(balance===null)fail('余额必须是非负数字');if(!['USD','CNY','EUR'].includes(v.currency))fail('币种无效');run('INSERT INTO snapshots VALUES(?,?,?,?,?,?,?,?,?)',uid(),v.account_id,v.currency,balance,num(v.granted),num(v.topped_up),v.source==='provider-api'?'provider-api':'manual',v.observed_at||now(),text(v.note,500));}
 function savePrice(v){const from=validDate(v.effective_from||now()),input=num(v.input_rate),cache=num(v.cached_rate),output=num(v.output_rate);if([input,cache,output].includes(null))fail('价格必须是非负数字');if(!/^https:\/\//.test(v.source_url||''))fail('请附上 HTTPS 价格来源');if(one('SELECT id FROM pricing WHERE provider=? AND model=? AND effective_from=?',v.provider,v.model,from))fail('此模型的生效日期已有价格版本');const id=uid('price-');run('INSERT INTO pricing VALUES (?,?,?,?,?,?,?,?,?,?)',id,required(v.provider,'provider'),required(v.model,'model'),input,cache,output,from,text(v.source_url,600),text(v.note,1000),now());return{id}}
 function saveBudget(v){const id=text(v.id)||uid('budget-');if(!['all','project','provider','account_id'].includes(v.scope))fail('预算范围无效');if(v.scope!=='all'&&!text(v.scope_id))fail('预算对象不能为空');const amount=num(v.amount),threshold=num(v.threshold)??.8;if(!amount||threshold<=0||threshold>1)fail('预算或提醒比例无效');run('INSERT OR REPLACE INTO budgets VALUES (?,?,?,?,?,?,?,?,?)',id,required(v.name,'名称'),v.scope,text(v.scope_id),v.period==='daily'?'daily':'monthly',amount,threshold,v.enabled===false||v.enabled===0?0:1,now());return{id}}
 function budgets(){return all('SELECT * FROM budgets ORDER BY created_at').map(b=>{const today=localDay(),start=b.period==='daily'?today:today.slice(0,7)+'-01';const rows=filtered({from:start,to:today,...(b.scope==='all'?{}:{[b.scope]:b.scope_id})});const s=stats(rows);return{...b,spent:s.cost_high,spent_low:s.cost_low,known_cost:s.known_cost,total_calls:s.count,ratio:s.cost_high===null?null:s.cost_high/b.amount,period_start:start}})}
 function alert(id,type,title,detail,severity='warning'){run(`INSERT INTO alerts VALUES(?,?,?,?,?,'open',?,?,NULL) ON CONFLICT(id) DO UPDATE SET title=excluded.title,detail=excluded.detail,severity=excluded.severity,last_seen=excluded.last_seen,status=CASE WHEN alerts.status='resolved' THEN 'open' ELSE alerts.status END`,id,type,title,detail,severity,now(),now())}
 function evaluateAlerts(){
  const active=new Set();
  const emit=(id,...args)=>{active.add(id);alert(id,...args)};
  for(const b of budgets())if(b.enabled&&b.ratio!==null&&b.ratio>=b.threshold)emit(`budget:${b.id}:${b.period_start}`,'budget',`${b.name} · ${b.ratio>=1?'预算已超出':'接近预算'}`,`本周期已知估算上限 $${b.spent.toFixed(4)} / $${b.amount}；已覆盖 ${b.known_cost}/${b.total_calls} 条记录。`,b.ratio>=1?'critical':'warning');
  for(const a of accounts()){
   for(const snapshot of a.balances)if(a.enabled&&a.low_balance!==null&&snapshot.currency===a.currency&&snapshot.balance<a.low_balance)emit(`balance:${a.id}:${localDay()}`,'balance',`${a.name} 余额偏低`,`${snapshot.currency} ${snapshot.balance}；阈值 ${a.low_balance}。观测时间 ${snapshot.observed_at}`,'critical');
   if(a.enabled&&a.runway_days_estimate!==null&&a.runway_days_estimate<a.runway_days)emit(`runway:${a.id}:${localDay()}`,'runway',`${a.name} 预计可用天数不足`,`基于已观测 7 日估算费用，约 ${a.runway_days_estimate.toFixed(1)} 天。未采集调用、充值和价格变化可能改变结果。`);
   if(a.runway_unavailable_reason==='currency-mismatch')run("UPDATE alerts SET detail=? WHERE type='runway' AND status='open' AND id LIKE ?",'此提醒已解除：账户有非美元余额，不能用美元费用推算全部余额的可用天数。','runway:'+a.id+':%');
  }
  for(const old of all("SELECT id FROM alerts WHERE status='open' AND type IN ('budget','balance','runway')"))if(!active.has(old.id))run("UPDATE alerts SET status='resolved',last_seen=? WHERE id=?",now(),old.id);
  return all("SELECT * FROM alerts WHERE status='open' ORDER BY last_seen DESC");
 }

 function connector(id,name,kind,status,records=0,error=null,config={}){run(`INSERT INTO connectors VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,last_seen=excluded.last_seen,last_error=excluded.last_error,records=excluded.records,config=excluded.config`,id,name,kind,status,now(),error,records,json(config))}
 return{db,dir,all,one,run,setting,setSetting,ingest,filtered,dashboard,listCalls,trace,accounts,saveAccount,snapshot,savePrice,saveBudget,budgets,alert,evaluateAlerts,connector,close:()=>db.close()};
}
