// Localized system messages only; never translate account names or imported user data.
const messages=new Map(Object.entries({
'此提醒已解除：账户有非美元余额，不能用美元费用推算全部余额的可用天数。':'Resolved: the account has non-USD funds. USD spending cannot determine runway for the entire balance.',
'预算对象不能为空':'Select a budget target.','此模型的生效日期已有价格版本':'A price version already exists for this model and effective date.','请先登录':'Please sign in.','用户名或密码不正确':'Invalid username or password.','登录尝试过多，请 15 分钟后再试':'Too many login attempts. Try again in 15 minutes.','来源无效':'Invalid request origin.','仅允许同源请求':'Only same-origin requests are allowed.','采集凭据无效':'Invalid ingestion credential.','接口不存在':'Endpoint not found.','服务处理失败，请查看服务日志':'The request failed. Check the server logs.','当前密码不正确':'Current password is incorrect.','新密码至少 12 位，最多 200 位':'New password must contain 12–200 characters.','调用记录必须是对象':'Each observation must be an object.','不支持的 provider':'Unsupported provider.','status 无效':'Invalid request status.','无效日期':'Invalid date.','日期范围无效':'Invalid date range.','每批最多 1000 条调用':'Send at most 1,000 observations per batch.','Trace 不存在':'Trace not found.','Provider 无效':'Invalid provider.','账户不存在':'Account not found.','余额必须是非负数字':'Balance must be a non-negative number.','币种无效':'Invalid currency.','价格必须是非负数字':'Prices must be non-negative numbers.','请附上 HTTPS 价格来源':'Provide an HTTPS pricing source.','预算范围无效':'Invalid budget scope.','预算或提醒比例无效':'Invalid budget or alert threshold.','请先配置 DeepSeek API key':'Configure a DeepSeek API key first.','需配置 OpenAI Organization Admin API key 才能读取账单；普通推理 Key 的调用记录仍可正常采集':'Configure an OpenAI Organization Admin API key to read billing. Telemetry with an inference key still works.','提供方未返回余额结构':'The provider did not return a balance structure.','提供方分页缺少游标':'The provider omitted a pagination cursor.','账户记录超过本次同步范围':'Account records exceed the synchronization limit.','请缩小日期范围，每次导出最多 100,000 条':'Narrow the date range. Export supports at most 100,000 rows.','请提供最多 10,000 行账单':'Provide at most 10,000 billing rows.','账单日期格式为 YYYY-MM-DD':'Use YYYY-MM-DD for billing dates.','账单金额无效':'Invalid statement amount.','请提供真实调用记录数组':'Provide an array of real observations.','Webhook 必须使用 HTTPS':'Webhook must use HTTPS.','尚未配置 webhook':'No webhook is configured.','账户余额需手动录入':'Record a manual balance snapshot.','模型成本区间无效':'Invalid cost range.','提供方返回账单金额无效':'Invalid provider billing amount.',
'Organization Admin API key 用于账单；推理 Key 不能替代':'An Organization Admin API key is required for billing; an inference key cannot replace it.','普通 API key 可读取账户余额':'A standard API key can read account balance.','调用用量经 SDK 采集；账单通过 JSON/CSV 导入，余额支持手动快照':'SDK usage collection, JSON/CSV billing imports and manual balance snapshots.','调用用量经 SDK 采集；公开余额接口尚未确认，支持手动快照':'SDK usage collection. No public balance endpoint verified; manual snapshots supported.','SystemOne usage 由调用返回；公开 OpenAPI 没有账户余额接口':'SystemOne returns usage per request; the public OpenAPI has no balance endpoint.','订阅 Token 单列，不伪装成免费 API；支持已报告用量导入':'Subscription tokens are separate, not free API usage. Reported usage can be imported.','使用标准采集 API / JSON 导入':'Use the standard ingestion API or JSON import.'
}));
export function englishMessage(s){if(typeof s!=='string')return s;if(messages.has(s))return messages.get(s);return s
 .replace(/^(.*)不能为空$/,'$1 is required.')
 .replace(/^已读取 (\d+) 个币种余额$/,'Read balances in $1 currencies.')
 .replace(/^已同步 (\d+) 条本月官方账单（UTC 日桶）/,'Synced $1 provider statement lines for this month (UTC days)')
 .replace('；用量明细未取得：','; usage details unavailable: ')
 .replace(/HTTP (\d+)：凭据无效或缺少账户读取权限/,'HTTP $1: invalid credential or missing account-read permission')
 .replace(/提供方返回 HTTP (\d+)/,'Provider returned HTTP $1')
 .replace('余额偏低','balance is low').replace('预计可用天数不足','estimated runway is low').replace('预算已超出','budget exceeded').replace('接近预算','budget threshold reached')
 .replace(/本周期已知估算上限 (.*?)；已覆盖 (.*?) 条记录。/,'Known upper estimate this period: $1; priced $2 observations.')
 .replace(/；阈值 (.*?)。观测时间 (.*)/,'; threshold $1. Observed at $2')
 .replace(/基于已观测 7 日估算费用，约 (.*?) 天。未采集调用、充值和价格变化可能改变结果。/,'Approximately $1 days based on observed 7-day estimates. Missing calls, top-ups and price changes may affect this.');}
const fields=new Set(['error','last_error','detail','title','credential']);
export function localizePayload(value,key=''){if(typeof value==='string')return fields.has(key)?englishMessage(value):value;if(Array.isArray(value))return value.map(v=>localizePayload(v));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,localizePayload(v,k)]));return value}
export function languageMiddleware(req,res,next){if(String(req.headers['accept-language']||'').toLowerCase().startsWith('en')){const send=res.json.bind(res);res.json=value=>send(localizePayload(value))}next()}
