import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import express from 'express';
import {createStore} from './db.mjs';
import {createSecrets,authMiddleware} from './auth.mjs';
import {createProviderSync,capabilities} from './providers.mjs';
import {createCollector} from './importers.mjs';
import {languageMiddleware} from './i18n.mjs';
import {now,uid,json,parse,range,csv,num,text,fail} from './lib.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export function createApp({dataDir=process.env.FINOPS_DATA||path.join(root,'.local'),fetchImpl=fetch,scheduler=true}={}){
 const store=createStore(dataDir),secrets=createSecrets(dataDir),auth=authMiddleware(store,secrets),sync=createProviderSync(store,secrets,fetchImpl),collector=createCollector(store,dataDir);const app=express();app.disable('x-powered-by');app.set('trust proxy','loopback');
 app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY','Cache-Control':'no-store'});next()});
 app.use(languageMiddleware);app.use(express.json({limit:'4mb'}));app.use(auth.checkOrigin);
 app.get('/health',(req,res)=>res.json({ok:true,application:'LLMFinOps',version:'0.1.0',revision:process.env.FINOPS_REVISION||'local'}));
 const cleanBalancePrefs=value=>{const out={},accounts=new Set(store.accounts().map(a=>a.id));if(!value||typeof value!=='object'||Array.isArray(value))return out;for(const[id,list]of Object.entries(value)){if(!accounts.has(id)||!Array.isArray(list))continue;const currencies=[...new Set(list.filter(c=>['USD','EUR','CNY'].includes(c)))];if(currencies.length)out[id]=currencies}return out};
 const balancePrefs=()=>cleanBalancePrefs(store.setting('balance_visibility_hidden',{}));
 const widgetSummary=req=>{const hidden=balancePrefs(),items=store.accounts().map(a=>({id:a.id,name:a.name,provider:a.provider,billing_mode:a.billing_mode,balances:a.balances.filter(b=>!(hidden[a.id]||[]).includes(b.currency)).map(b=>({currency:b.currency,balance:b.balance,source:b.source,observed_at:b.observed_at}))}));const observed=items.flatMap(a=>a.balances.map(b=>b.observed_at)).filter(Boolean).sort().at(-1)||null;return{version:1,generated_at:now(),updated_at:observed,open_url:`https://${req.get('host')}/#overview`,accounts:items}};
 app.get('/api/widget/summary',auth.widget,(req,res)=>res.json(widgetSummary(req)));
 app.get('/api/session',(req,res)=>res.json({authenticated:!!auth.authenticated(req),user:auth.authenticated(req)?{name:'Jingxuan',username:'admin'}:null}));
 app.post('/api/login',auth.login);app.post('/api/logout',auth.logout);
 app.post('/api/v1/calls',auth.ingest,(req,res)=>{const result=store.ingest(req.body.calls||[req.body]);const source=text(req.body.source)||'push-sdk';store.connector(source,source,'push','connected',store.one('SELECT COUNT(*) n FROM calls WHERE source=?',source)?.n||result.inserted);res.status(202).json(result)});
 app.post('/api/v1/heartbeat',auth.ingest,(req,res)=>{const id=text(req.body.id);if(!id)fail('id 必填');store.connector(id,text(req.body.name)||id,'push','connected',num(req.body.records)||0,null,{dropped:num(req.body.dropped)||0,spool_pending:num(req.body.pending)||0});res.json({ok:true})});
 app.use('/api',auth.require);
 app.get('/api/overview',(req,res)=>res.json(store.dashboard(req.query)));
 app.get('/api/calls',(req,res)=>res.json(store.listCalls(req.query)));
 app.get('/api/calls/export',(req,res)=>{const rows=store.filtered(req.query);if(rows.length>100000)fail('请缩小日期范围，每次导出最多 100,000 条');res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="llmfinops-calls.csv"'}).send(csv(rows,['id','trace_id','project','environment','provider','account_id','feature','model','started_at','status','duration_ms','input_tokens','cached_tokens','output_tokens','reasoning_tokens','total_tokens','cost_low','cost_high','cost_source','scope','source']))});
 app.get('/api/traces/:id',(req,res)=>res.json(store.trace(req.params.id)));
 app.get('/api/accounts',(req,res)=>res.json({items:store.accounts().map(a=>({...a,has_key:!!secrets.resolve(a.id),has_admin_key:!!secrets.resolve(a.id,'adminKey'),capabilities:capabilities[a.provider]})),capabilities}));
 app.get('/api/preferences/balances',(req,res)=>res.json({hidden:balancePrefs()}));
 app.post('/api/preferences/balances',(req,res)=>{const hidden=cleanBalancePrefs(req.body?.hidden||{});store.setSetting('balance_visibility_hidden',hidden);res.json({hidden})});
 app.post('/api/accounts',(req,res)=>{const a=store.saveAccount(req.body);if(req.body.api_key||req.body.admin_key)secrets.setAccount(a.id,{...(req.body.api_key?{key:text(req.body.api_key,1000)}:{}),...(req.body.admin_key?{adminKey:text(req.body.admin_key,1000)}:{})});res.json({id:a.id})});
 app.delete('/api/accounts/:id',(req,res)=>{const result=store.deleteAccount(req.params.id);secrets.removeAccount(req.params.id);store.evaluateAlerts();res.json(result)});
 app.post('/api/accounts/:id/sync',async(req,res)=>res.json(await sync.sync(req.params.id)));
 app.post('/api/accounts/:id/snapshot',(req,res)=>{store.snapshot({...req.body,account_id:req.params.id,source:'manual'});store.evaluateAlerts();res.json({ok:true})});
 app.post('/api/sync',async(req,res)=>{const imports=await collector.run();const accounts=await sync.syncAll();res.json({imports,accounts})});
 app.get('/api/billing',(req,res)=>{const{start,end}=range(req.query);let where='b.day>=? AND b.day<=?',args=[start,end];if(req.query.provider){where+=' AND a.provider=?';args.push(String(req.query.provider))}if(req.query.account_id){where+=' AND b.account_id=?';args.push(String(req.query.account_id))}const rows=store.all('SELECT b.*,a.name account_name,a.provider FROM billing_daily b LEFT JOIN accounts a ON a.id=b.account_id WHERE '+where+' ORDER BY b.day DESC',...args);res.json({items:rows,totals:[...new Set(rows.map(x=>x.currency))].map(currency=>({currency,amount:rows.filter(x=>x.currency===currency).reduce((s,x)=>s+x.amount,0)})),range:{start,end,timezone:'UTC / source billing timezone'},runs:store.all('SELECT * FROM sync_runs ORDER BY started_at DESC LIMIT 20')})});
 app.post('/api/billing/import',(req,res)=>{const rows=req.body.rows;if(!Array.isArray(rows)||rows.length>10000)fail('请提供最多 10,000 行账单');const data=rows.map(r=>{if(!store.one('SELECT id FROM accounts WHERE id=?',r.account_id))fail('账户不存在');if(!/^\d{4}-\d{2}-\d{2}$/.test(r.day))fail('账单日期格式为 YYYY-MM-DD');if(!['USD','EUR','CNY'].includes(r.currency))fail('币种无效');if(!Number.isFinite(Number(r.amount)))fail('账单金额无效');return[json([r.account_id,r.day,r.provider_project||'',r.line_item||'',r.currency]),r.account_id,r.day,text(r.provider_project),text(r.line_item),r.currency,Number(r.amount),'statement-import',now()]});store.db.exec('BEGIN');try{for(const row of data)store.run('INSERT OR REPLACE INTO billing_daily VALUES (?,?,?,?,?,?,?,?,?)',...row);store.db.exec('COMMIT')}catch(e){store.db.exec('ROLLBACK');throw e}res.json({imported:data.length})});
 app.get('/api/pricing',(req,res)=>res.json({items:store.all('SELECT * FROM pricing ORDER BY provider,model,effective_from DESC')}));
 app.post('/api/pricing',(req,res)=>res.json(store.savePrice(req.body)));
 app.get('/api/budgets',(req,res)=>res.json({items:store.budgets()}));
 app.post('/api/budgets',(req,res)=>{const b=store.saveBudget(req.body);store.evaluateAlerts();res.json(b)});
 app.delete('/api/budgets/:id',(req,res)=>{store.run('DELETE FROM budgets WHERE id=?',req.params.id);res.json({ok:true})});
 app.get('/api/alerts',(req,res)=>res.json({items:store.all('SELECT * FROM alerts ORDER BY last_seen DESC LIMIT 300')}));
 app.post('/api/alerts/:id/ack',(req,res)=>{store.run("UPDATE alerts SET status='acknowledged',ack_at=? WHERE id=?",now(),req.params.id);res.json({ok:true})});
 app.get('/api/integrations',(req,res)=>res.json({items:store.all('SELECT * FROM connectors ORDER BY name').map(c=>({...c,config:parse(c.config,{})})),ingest_path:'/api/v1/calls',scheduler:{collection_seconds:60,account_sync_minutes:15,enabled:scheduler},not_collected:'不采集 prompt、回复正文、CV、邮件内容、API key。只存调用与账务元数据。'}));
 app.post('/api/import',(req,res)=>{const calls=req.body.calls;if(!Array.isArray(calls)||calls.some(c=>c.source==='demo'))fail('请提供真实调用记录数组');res.json(store.ingest(calls))});
 app.post('/api/collect',async(req,res)=>res.json(await collector.run()));
 app.get('/api/settings',(req,res)=>res.json({version:'0.1.0',timezone:'Europe/Paris',currency:'USD',retention:'保留历史账本；不自动删除',has_webhook:!!secrets.notification().url,counts:{calls:store.one('SELECT COUNT(*) n FROM calls').n,accounts:store.one("SELECT COUNT(*) n FROM accounts WHERE sync_status<>'deleted'").n},data_directory_configured:true}));
 app.post('/api/settings/password',(req,res)=>{secrets.setPassword(req.body.current,req.body.password);store.run('DELETE FROM sessions');res.json({ok:true,relogin:true})});
 app.post('/api/settings/ingest-token',(req,res)=>res.json({token:secrets.token()}));
 app.post('/api/settings/widget-token',(req,res)=>res.json({token:secrets.widgetToken()}));
 app.post('/api/settings/widget-token/rotate',(req,res)=>res.json({token:secrets.rotateWidgetToken()}));
 app.post('/api/settings/webhook',(req,res)=>{let url=text(req.body.url,1200);if(url&&!url.startsWith('https://'))fail('Webhook 必须使用 HTTPS');secrets.setNotification({url});res.json({ok:true})});
 app.post('/api/settings/webhook/test',async(req,res)=>{const url=secrets.notification().url;if(!url)fail('尚未配置 webhook');const r=await fetchImpl(url,{method:'POST',headers:{'content-type':'application/json'},body:json({event:'llmfinops.test',title:'LLMFinOps 通知测试',at:now()}),signal:AbortSignal.timeout(10000)});if(!r.ok)fail(`Webhook HTTP ${r.status}`,502);res.json({ok:true})});
 app.use('/api',(req,res)=>res.status(404).json({error:'接口不存在'}));
 const dist=path.join(root,'dist');app.use(express.static(dist,{index:false}));app.get('/{*path}',(req,res)=>{if(!fs.existsSync(path.join(dist,'index.html')))return res.status(503).send('请运行 npm run build，或通过开发服务器 43910 访问。');res.sendFile(path.join(dist,'index.html'))});
 app.use((e,req,res,next)=>{if(res.headersSent)return next(e);res.status(e.status||500).json({error:e.status?e.message:'服务处理失败，请查看服务日志'});if(!e.status)console.error('[LLMFinOps]',e.name,e.message)});
 let count=0,busy=false;const scheduled=async()=>{if(busy)return;busy=true;try{await collector.run();if(count++%15===0)await sync.syncAll();const alerts=store.evaluateAlerts(),url=secrets.notification().url;if(url){for(const a of alerts){if(store.setting('notified:'+a.id,false))continue;try{const r=await fetchImpl(url,{method:'POST',headers:{'content-type':'application/json'},body:json({event:'llmfinops.alert',alert:a}),signal:AbortSignal.timeout(10000)});if(r.ok)store.setSetting('notified:'+a.id,true)}catch{}}}}catch(e){console.error('[scheduler]',e.message)}finally{busy=false}};
 const timer=scheduler?setInterval(scheduled,60000):null;timer?.unref();const initial=scheduler?setTimeout(scheduled,1500):null;initial?.unref();
 return{app,store,secrets,sync,collector,close:()=>{if(timer)clearInterval(timer);if(initial)clearTimeout(initial);auth.close();store.close()}};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const system=createApp();const port=Number(process.env.PORT||43911),host=process.env.HOST||'127.0.0.1';const server=system.app.listen(port,host,()=>console.log(`LLMFinOps listening ${host}:${port}`));for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>server.close(()=>{system.close();process.exit(0)}));}
