import React,{useEffect,useRef,useState}from'react';import{X,LoaderCircle,Inbox,Info,Check,Copy,AlertTriangle,RefreshCw}from'lucide-react';import{useI18n,useLabel}from'./i18n.jsx';
export const PROVIDERS=[{id:'openai',name:'OpenAI',short:'O',color:'#70ad90'},{id:'deepseek',name:'DeepSeek',short:'D',color:'#7699ed'},{id:'gemini',name:'Gemini',short:'G',color:'#b49be6'},{id:'mimo',name:'MiMo',short:'M',color:'#e7a478'},{id:'jev',name:'Jev',short:'J',color:'#d992b2'},{id:'codex',name:'Codex',short:'C',color:'#9aafc2'},{id:'other',name:'Other',short:'+',color:'#a0a8b8'}];
export function ProviderIcon({id,size=''}){const p=PROVIDERS.find(p=>p.id===id)||PROVIDERS.at(-1);return <span className={'provider-icon '+size} style={{'--provider-color':p.color}}>{p.short}</span>}
export function Badge({value,children}){const label=useLabel();return <span className={'badge '+(value||'neutral')}><i/>{children||label(value)}</span>}
export function Button({children,icon:Icon,variant='',loading=false,className='',...props}){return <button {...props} disabled={props.disabled||loading} className={'button '+variant+' '+className}>{loading?<LoaderCircle size={16} className="spin"/>:Icon?<Icon size={16}/>:null}{children}</button>}
export function Panel({title,subtitle,action,children,className=''}){return <section className={'panel '+className}>{(title||action)&&<div className="panel-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>}
export function Empty({title,description,action}){const{t}=useI18n();return <div className="empty"><div className="empty-mark"><Inbox size={25}/></div><h3>{title||t('这个范围内还没有记录','No records in this range')}</h3><p>{description||t('连接数据源，或选择更长的日期范围。未采集不等于没有调用。','Connect a source or choose a wider date range. Missing data does not mean no usage.')}</p>{action}</div>}
export function Loading(){const{t}=useI18n();return <div className="loading"><LoaderCircle className="spin" size={22}/><span>{t('正在读取账本','Loading your ledger')}</span></div>}
export function ErrorBox({error,retry}){const{t}=useI18n();return <div className="notice danger"><AlertTriangle size={18}/><span>{error}</span>{retry&&<Button onClick={retry} icon={RefreshCw}>{t('重试','Retry')}</Button>}</div>}
export function Notice({children}){return <div className="notice"><Info size={17}/><span>{children}</span></div>}
export function Field({label,hint,children,className=''}){return <label className={'field '+className}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Modal({title,subtitle,onClose,children,wide=false}){const ref=useRef();const{t}=useI18n();useEffect(()=>{const previous=document.activeElement,old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=ref.current?.querySelectorAll('button:not(:disabled),input,select,textarea,a[href],[tabindex="0"]');if(!els?.length)return;if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els[els.length-1].focus()}else if(!e.shiftKey&&document.activeElement===els[els.length-1]){e.preventDefault();els[0].focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus()}},[]);return <div className="modal-backdrop" onClick={onClose}><section ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} className={'modal '+(wide?'wide':'')} onClick={e=>e.stopPropagation()}><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label={t('关闭','Close')} onClick={onClose}><X/></button></header><div className="modal-body">{children}</div></section></div>}
export function CopyButton({value}){const{t}=useI18n(),[copied,setCopied]=useState(false);return <Button icon={copied?Check:Copy} onClick={async()=>{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1800)}}>{copied?t('已复制','Copied'):t('复制','Copy')}</Button>}
export function Metric({label,value,detail,icon:Icon,tone='',children}){return <div className={'metric '+tone}><div className="metric-label">{label}{Icon&&<Icon size={17}/>}</div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div>{children}</div>}
export function Meter({value,color}){return <div className="meter"><i style={{width:Math.max(0,Math.min(100,(value||0)*100))+'%',...(color?{background:color}:{})}}/></div>}
export function FormError({error}){return error?<ErrorBox error={error}/>:null}
